---
- name: Deploy application to server
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    ansistrano_deploy_to: "/home/ttarnawski/domains/ratebtn.ttarnawski.usermd.net/public_html"
    ansistrano_deploy_from: "{{ playbook_dir }}/../artifact.tar"
    ansistrano_deploy_via: "copy_unarchive"
    ansistrano_current_via: "rsync"
    ansistrano_allow_anonymous_stats: no
    ansistrano_keep_releases: 5
  roles:
    - { role: ansistrano.deploy }
